CREATE TYPE "genero_enum" AS ENUM (
  'MASCULINO',
  'FEMININO',
  'OUTRO'
);

CREATE TYPE "tipo_benef_enum" AS ENUM (
  'BENEFICIARIO',
  'DOADOR',
  'BENEFICIARIO_DOADOR'
);

CREATE TYPE "nivel_acesso_enum" AS ENUM (
  'ADMINISTRADOR',
  'CONSULTOR'
);

CREATE TYPE "status_conta_enum" AS ENUM (
  'CONTA_APROVADA',
  'CONTA_NEGADA',
  'CONTA_EM_ANALISE'
);

CREATE TYPE "status_doacao_enum" AS ENUM (
  'DOACAO_APTA',
  'DOACAO_NEGADA'
);

CREATE TYPE "tipo_relatorio_enum" AS ENUM (
  'DOACOES_RECEBIDAS',
  'DOACOES_DISTRIBUIDAS',
  'DOACOES_TODAS'
);

CREATE TABLE "estado" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "cidade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "estado_id" int NOT NULL
);

CREATE TABLE "endereco" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "logradouro" varchar NOT NULL,
  "numero" varchar NOT NULL,
  "complemento" varchar,
  "bairro" varchar,
  "cep" varchar,
  "cidade_id" int NOT NULL
);

CREATE TABLE "pessoa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "cpf" varchar UNIQUE NOT NULL,
  "rg" varchar,
  "genero" genero_enum NOT NULL,
  "tipo_beneficiario" tipo_benef_enum NOT NULL,
  "nascimento" date,
  "email" varchar,
  "endereco_id" int NOT NULL
);

CREATE TABLE "telefone" (
  "pessoa_id" int NOT NULL,
  "numero" varchar NOT NULL,
  PRIMARY KEY ("pessoa_id", "numero")
);

CREATE TABLE "funcionario" (
  "id" int PRIMARY KEY,
  "nivel_acesso" nivel_acesso_enum NOT NULL,
  "salario" decimal,
  "data_contratacao" date
);

CREATE TABLE "relatorio" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data_relatorio" date NOT NULL,
  "formato" varchar,
  "tipo_relatorio" tipo_relatorio_enum NOT NULL,
  "descricao" text,
  "funcionario_id" int NOT NULL
);

CREATE TABLE "beneficiario" (
  "id" int PRIMARY KEY,
  "limite" int,
  "cartao_benef" varchar,
  "status_conta" status_conta_enum NOT NULL
);

CREATE TABLE "categoria" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL
);

CREATE TABLE "produto" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "qualidade" boolean NOT NULL DEFAULT true
);

CREATE TABLE "doacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "instante" timestamp NOT NULL,
  "status_doacao" status_doacao_enum NOT NULL,
  "pessoa_id" int NOT NULL
);

CREATE TABLE "item_doacao" (
  "doacao_id" int NOT NULL,
  "produto_id" int NOT NULL,
  "quantidade" int NOT NULL,
  PRIMARY KEY ("doacao_id", "produto_id")
);

CREATE TABLE "categoria_produto" (
  "categoria_id" int NOT NULL,
  "produto_id" int NOT NULL,
  PRIMARY KEY ("categoria_id", "produto_id")
);

ALTER TABLE "cidade" ADD FOREIGN KEY ("estado_id") REFERENCES "estado" ("id");

ALTER TABLE "endereco" ADD FOREIGN KEY ("cidade_id") REFERENCES "cidade" ("id");

ALTER TABLE "pessoa" ADD FOREIGN KEY ("endereco_id") REFERENCES "endereco" ("id");

ALTER TABLE "telefone" ADD FOREIGN KEY ("pessoa_id") REFERENCES "pessoa" ("id");

ALTER TABLE "funcionario" ADD FOREIGN KEY ("id") REFERENCES "pessoa" ("id");

ALTER TABLE "relatorio" ADD FOREIGN KEY ("funcionario_id") REFERENCES "funcionario" ("id");

ALTER TABLE "beneficiario" ADD FOREIGN KEY ("id") REFERENCES "pessoa" ("id");

ALTER TABLE "doacao" ADD FOREIGN KEY ("pessoa_id") REFERENCES "pessoa" ("id");

ALTER TABLE "item_doacao" ADD FOREIGN KEY ("doacao_id") REFERENCES "doacao" ("id");

ALTER TABLE "item_doacao" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("id");

ALTER TABLE "categoria_produto" ADD FOREIGN KEY ("categoria_id") REFERENCES "categoria" ("id");

ALTER TABLE "categoria_produto" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("id");
